import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import NavBar from "@/app/NavBar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Metaversus',
    description: 'Generated by Ali Mohammadinia',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter.className} bg-primary-black overflow-hidden`}>
        <NavBar/>
        <main>
            {children}
        </main>
        </body>
        </html>
    )
}
